### ISSUE TITLE
vagrant-omnibus install failure

### ISSUE THREAD

**Issue by saturnflyer** [noahgibbs/madscience#18]
I've installed the gem with `sudo` to get over the #14 problem that I had.

Moving on and installing version 0.0.26 I've got this error:

```
$ sudo madscience setup
Running madscience 0.0.26...
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Installing apt (2.6.1)
Installing chef_handler (1.1.6)
Installing dmg (2.2.2)
Installing windows (1.36.6)
Installing vagrant (0.2.2)
Installing yum (3.5.3)
Installing virtualbox (0.7.2)
fatal: Not a git repository (or any of the parent directories): .git
/Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/chef-11.18.6/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Starting Chef Client, version 11.18.6
Compiling Cookbooks...
Converging 15 resources
Recipe: vagrant::mac_os_x
  * dmg_package[Vagrant] action install (up to date)
Recipe: vagrant::install_plugins
  * vagrant_plugin[vagrant-omnibus] action install

    ================================================================================
    Error executing action `install` on resource 'vagrant_plugin[vagrant-omnibus]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - vagrant

    Cookbook Trace:
    ---------------
    /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/cookbooks/vagrant/providers/plugin.rb:9:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/cookbooks/vagrant/recipes/install_plugins.rb

     23:     vagrant_plugin plugin['name'] do
     24:       user node['vagrant']['user']
     25:       version plugin['version']
     26:     end
     27:

    Compiled Resource:
    ------------------
    # Declared in /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/cookbooks/vagrant/recipes/install_plugins.rb:23:in `block in from_file'

    vagrant_plugin("vagrant-omnibus") do
      action :install
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name :vagrant
      recipe_name "install_plugins"
      version "1.4.1"
    end


Running handlers:
[2015-04-01T16:35:23-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-01T16:35:23-04:00] ERROR: Exception handlers complete
[2015-04-01T16:35:23-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 6.61052 seconds
[2015-04-01T16:35:23-04:00] ERROR: vagrant_plugin[vagrant-omnibus] (vagrant::install_plugins line 23) had an error: Errno::ENOENT: No such file or directory - vagrant
[2015-04-01T16:35:23-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
/Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/bin/madscience:84:in `block in do_local_setup': Failed during chef run! (RuntimeError)
    from /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/bin/madscience:51:in `in_madscience_dir'
    from /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/bin/madscience:79:in `do_local_setup'
    from /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.26/bin/madscience:143:in `<top (required)>'
    from /Users/jim/.rubies/ruby-2.2.1/bin/madscience:23:in `load'
    from /Users/jim/.rubies/ruby-2.2.1/bin/madscience:23:in `<main>'
```

**Comment by noahgibbs** [comment]
Exciting! I haven't seen this one, even when testing with halfway-broken stuff. Looks like a path problem. I'll investigate further.

Do me a favor - type "which vagrant" and see if it's in the obvious place (/usr/bin/vagrant). If so, see if it's symlinked to /opt/vagrant/bin/vagrant, which is the normal setup.

**Comment by noahgibbs** [comment]
Oh! And please type "sudo env | grep -i path" and put the output here. Let's see if you can see /usr/bin when sudo'd. Thanks!

**Comment by noahgibbs** [comment]
Looks like the Vagrant cookbook is using Chef's shell_out mixin. That mixin seems to be propagating the PATH through unmodified. That's probably good.

The Vagrant cookbook is also just running "vagrant" on the command line and assuming it can find it in the path. That makes sense -- the same cookbook is supposed to run on Windows and Linux, so they can't just assume /usr/bin/vagrant. I still may need to modify this to look in the right place, or take a configurable Vagrant binary path or something.

**Comment by noahgibbs** [comment]
Ah! And you're probably not alone in having this kind of problem -- while it's very common for /usr/bin to be present in the path and for that to be the first 'vagrant', it's not guaranteed. Okay, building a patch for this locally, I need to override the path.

Tests out locally, just pushed gem 0.0.27.

**Comment by saturnflyer** [comment]
Looks like I've got some duplicate paths in there.
This is 5 year old system which has plenty of my "I hope this works" configurations going on. (and I'm slowly cleaning up)

```
$ sudo env | grep -i path
PATH=/usr/local/heroku/bin:/usr/local/bin:/usr/local/share/npm/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/share/npm/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/share/npm/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/Users/jim/.gem/ruby/2.2.1/bin:/Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/bin:/Users/jim/.rubies/ruby-2.2.1/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/share/npm/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/texbin
```

Updated to 0.0.27 and the failure looks similar.

```
$ sudo madscience setup
Running madscience 0.0.27...
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Installing apt (2.6.1)
Installing chef_handler (1.1.6)
Installing dmg (2.2.2)
Installing windows (1.36.6)
Installing vagrant (0.2.2)
Installing yum (3.5.3)
Installing virtualbox (0.7.2)
fatal: Not a git repository (or any of the parent directories): .git
/Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/chef-11.18.6/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Starting Chef Client, version 11.18.6
Compiling Cookbooks...
Converging 15 resources
Recipe: vagrant::mac_os_x
  * dmg_package[Vagrant] action install (up to date)
Recipe: vagrant::install_plugins
  * vagrant_plugin[vagrant-omnibus] action install

    ================================================================================
    Error executing action `install` on resource 'vagrant_plugin[vagrant-omnibus]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - vagrant

    Cookbook Trace:
    ---------------
    /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/cookbooks/vagrant/providers/plugin.rb:9:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/cookbooks/vagrant/recipes/install_plugins.rb

     23:     vagrant_plugin plugin['name'] do
     24:       user node['vagrant']['user']
     25:       version plugin['version']
     26:     end
     27:

    Compiled Resource:
    ------------------
    # Declared in /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/cookbooks/vagrant/recipes/install_plugins.rb:23:in `block in from_file'

    vagrant_plugin("vagrant-omnibus") do
      action :install
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name :vagrant
      recipe_name "install_plugins"
      version "1.4.1"
    end


Running handlers:
[2015-04-01T17:28:56-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-01T17:28:56-04:00] ERROR: Exception handlers complete
[2015-04-01T17:28:56-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 7.07876 seconds
[2015-04-01T17:28:56-04:00] ERROR: vagrant_plugin[vagrant-omnibus] (vagrant::install_plugins line 23) had an error: Errno::ENOENT: No such file or directory - vagrant
[2015-04-01T17:28:56-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
/Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/bin/madscience:84:in `block in do_local_setup': Failed during chef run! (RuntimeError)
    from /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/bin/madscience:51:in `in_madscience_dir'
    from /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/bin/madscience:79:in `do_local_setup'
    from /Users/jim/.rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/madscience-0.0.27/bin/madscience:143:in `<top (required)>'
    from /Users/jim/.rubies/ruby-2.2.1/bin/madscience:23:in `load'
    from /Users/jim/.rubies/ruby-2.2.1/bin/madscience:23:in `<main>'
```

**Comment by noahgibbs** [comment]
Well, you have /usr/bin in your path. So that's not the problem. Is there a symlink in /usr/bin/vagrant pointing to /opt/vagrant/bin/vagrant? And can you find it with "which vagrant"? Or perhaps "sudo which vagrant"?

**Comment by saturnflyer** [comment]
Sorry. I forgot to leave that info. Both with and without sudo, my system has no `vagrant`

**Comment by noahgibbs** [comment]
Interesting. So the problem is that the Chef cookbook thinks it's installing Vagrant, but isn't. Do you see an /opt/vagrant directory on your file system?

**Comment by noahgibbs** [comment]
Can you try installing Vagrant 1.7.1 manually and see if it works?

**Comment by noahgibbs** [comment]
Hm. You mentioned this is an older machine, configured slightly oddly.

Is it possible that you've had Vagrant installed before on this machine, and you've done a "manual uninstall"? (Like, removed /opt/vagrant yourself?)

Vagrant has this slightly weird thing it does where it stores a system setting on Mac OS to decide whether it's installed. And if you don't blow that away, it doesn't install again.

I need to think about this. There are probably other users that have done that even if you haven't. I feel a pull request to the Vagrant cookbook coming on.

**Comment by saturnflyer** [comment]
Yes. That is definitely the case. I haven't had a chance to manually install vagrant yet...

**Comment by noahgibbs** [comment]
Try this command: "sudo pkgutil --forget com.vagrant.vagrant"

That will allow it to install again.

**Comment by saturnflyer** [comment]
Huzzah! that command did it!

**Comment by noahgibbs** [comment]
Excellent! Yeah, I'll see if there's a sane way for me to work that into the Vagrant cookbook. Right now that's a fairly mysterious case, which is no good.
